[package]
name = "actix-share-listener-sample"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
nix = { version = "0.29", features = ["socket", "uio", "process"] }
tokio = { version = "1", features = ["full"] }
